// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const { themes } = require('prism-react-renderer');
const path = require('path');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Document - FluxBuilder - An Ultimate Approach For Flutter Mobile Apps",
  tagline: "",
  url: "https://docs.fluxbuilder.com",
  baseUrl: "/",
  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",
  favicon: "img/favicon.ico",

  organizationName: "fluxbuilder-docs", // Usually your GitHub org/user name.
  projectName: "fluxbuilder-docs.github.io", // Usually your repo name.
  deploymentBranch: "gh-pages",

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/", // Serve the docs at the site's root
          sidebarPath: require.resolve('./sidebars.js'), //  `undefined` to create a fully autogenerated 
        }, 
        blog: false,
        theme: {
          customCss: [
            require.resolve("./css/docu-notion-styles.css"),
            require.resolve(
              "./css/gifplayer.css"
              //"./node_modules/react-gif-player/dist/gifplayer.css" // this gave a big red compile warning which is seaming unrelated "  Replace Autoprefixer browsers option to Browserslist config..."
            ),
          ],
        },
        gtag: {
          trackingID: 'G-QKWPZEM3TZ',
          anonymizeIP: true,
        },
      }),
    ],
  ],
  i18n: {
    defaultLocale: "en",
    locales: ["en", "zh", "hi", "es", "fr", "ar", "bn", "ru", "pt", "vi"],
    localeConfigs: {
      en: {
        label: "English",
        direction: "ltr",
        htmlLang: "en-US",
        calendar: "gregory",
      },
      zh: {
        label: "中文 (Chinese)",
        direction: "ltr",
        htmlLang: "zh-CN",
        calendar: "gregory",
      },
      hi: {
        label: "हिन्दी (Hindi)",
        direction: "ltr",
        htmlLang: "hi-IN",
        calendar: "gregory",
      },
      es: {
        label: "Español (Spanish)",
        direction: "ltr",
        htmlLang: "es-ES",
        calendar: "gregory",
      },
      fr: {
        label: "Français (French)",
        direction: "ltr",
        htmlLang: "fr-FR",
        calendar: "gregory",
      },
      ar: {
        label: "العربية (Arabic)",
        direction: "rtl",
        htmlLang: "ar-SA",
        calendar: "gregory",
      },
      bn: {
        label: "বাংলা (Bengali)",
        direction: "ltr",
        htmlLang: "bn-BD",
        calendar: "gregory",
      },
      ru: {
        label: "Русский (Russian)",
        direction: "ltr",
        htmlLang: "ru-RU",
        calendar: "gregory",
      },
      pt: {
        label: "Português (Portuguese)",
        direction: "ltr",
        htmlLang: "pt-BR",
        calendar: "gregory",
      },
      vi: {
        label: "Tiếng Việt (Vietnamese)",
        direction: "ltr",
        htmlLang: "vi-VN",
        calendar: "gregory",
      },
    },
  },
  themes: [
    // ... Your other themes.
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        // ... Your options.
        // `hashed` is recommended as long-term-cache of index file is possible.
        hashed: true,
        language: ["en", "zh", "es", "fr", "ru", "pt", "vi"],
        indexBlog: false,
        indexPages: false,
        docsRouteBasePath: "/",
      },
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      metadata: [
        {
          name: "keywords",
          content: "Document - FluxBuilder - An Ultimate Approach For Flutter Mobile Apps",
        },
      ],
    
      sitemap: {
        // https://www.sitemaps.org/protocol.html#xmlTagDefinitions
        changefreq: "weekly",
        priority: 0.5,
        ignorePatterns: [],
      },
      navbar: {
        title: "",
        hideOnScroll: true,
        logo: {
          alt: "Logo",
          src: "img/logo.png",
          srcDark: 'img/logo_dark.png',
          href: 'https://fluxbuilder.com',
          target: '_self',
        },

        items: [
          {
            href: 'https://fluxbuilder.com',
            position: 'right',
            className: 'header-link',
            label: 'Home',
          },
          {
            href: 'https://fluxbuilder.com/feature',
            position: 'right',
            className: 'header-link',
            label: 'Feature',
          },
          {
            href: 'https://fluxbuilder.com/agency',
            position: 'right',
            className: 'header-link',
            label: 'Agency',
          },
          {
            href: 'https://fluxbuilder.com/pricing',
            position: 'right',
            className: 'header-link',
            label: 'Pricing',
          },
          {
            href: 'https://docs.fluxbuilder.com',
            position: 'right',
            className: 'header-link active',
            label: 'Docs',
          },
          {
            href: 'https://fluxbuilder.com/pricing',
            position: 'right',
            className: 'header-link',
            label: 'Profile',
          },
          {
            type: 'localeDropdown',
            position: 'right',
          },
          {
            type: 'search',
            position: 'left',
          },
        ],
      }, 
      
      footer: {
        style: 'light',
        logo: {
          alt: 'InspireUI',
          src: '/img/logo.png',
          href: 'https://www.fluxbuilder.com',
          width: 160,
          height: 36,
        },
        copyright: `Copyright © ${new Date().getFullYear()} <a href="https://inspireui.com">InspireUI Ltd.</a>`, // You can also put own HTML here
      }, 

      prism: {
        theme: themes.github,
        darkTheme: themes.dracula,
      },
    }),
};

module.exports = config;
